version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: rq
    versions:
    - 1.7.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
  - dependency-name: redislite
    versions:
    - 6.0.674960
  - dependency-name: flask-testing
    versions:
    - 0.8.1
