# https://traefik.io/blog/traefik-2-0-docker-101-fc2893944b9d/
# https://juliensalinas.com/en/traefik-reverse-proxy-docker-compose-docker-swarm-nlpcloud/

version: "3.9"

# Define networks
networks:
  # Use the external network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
  # Local network
  opennews:

# Define volumes
volumes:
  redis:

# Use external Docker secrets
secrets:
  vault_token:
    external: true
  vault_keys_csv:
    external: true



services:

  # Service for the OpenNews api
  api:
    image: spamz23/opennews:api

    # Command to start the server at port 8000
    command: gunicorn opennews.wsgi:application -b 0.0.0.0:8000

    deploy:
      labels:
        - traefik.enable=true
        # Use the traefik-public network
        - traefik.docker.network=traefik-public
        # Add required label for traefik (Traefik will only use services with this label)
        - traefik.constraint-label=traefik-public
        # Routing
        - traefik.http.routers.opennews-api.tls=true
        - traefik.http.routers.opennews-api.entrypoints=websecure
        - traefik.http.routers.opennews-api.rule=Host(`api.onews.dsilva.dev`)
        - traefik.http.services.opennews-api.loadbalancer.server.port=8000

    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public
      - opennews

    environment:
      # Use production settings
      DJANGO_SETTINGS_MODULE: opennews.settings.production
      VAULT_URL: http://vault:8200/
      VAULT_TOKEN: /run/secrets/vault_token # --------|
      VAULT_KEYS_CSV: /run/secrets/vault_keys_csv # --|-->File location of Docker secret
      CELERY_BROKER_URL: redis://redis:6379/ # -----|
      CELERY_RESULT_BACKEND: redis://redis:6379/ #--|--> 'redis' (instead of e.g. localhost) because it is the name of the redis service

    # Mount secrets from Swarm Manager
    secrets:
      - vault_token
      - vault_keys_csv


  # Redis database to serve as a message broker between backend
  # and celeris worker
  redis:
    image: "redis:alpine"
    volumes:
      - "redis:/data"
    # Add to local network
    networks:
      - opennews

  # Celery background worker
  celery:
    image: spamz23/opennews:api
    command: celery -A opennews worker -l info

    environment:
      # Use production settings
      DJANGO_SETTINGS_MODULE: opennews.settings.production
      VAULT_URL: http://vault:8200/
      VAULT_TOKEN: /run/secrets/vault_token # --------|
      VAULT_KEYS_CSV: /run/secrets/vault_keys_csv # --|-->File location of Docker secret
      CELERY_BROKER_URL: redis://redis:6379/ # -----|
      CELERY_RESULT_BACKEND: redis://redis:6379/ #--|--> 'redis' (instead of e.g. localhost) because it is the name of the redis service
    
    # Add to local network and public network
    networks:
      - opennews
      - traefik-public

    # Mount secrets from Swarm Manager
    secrets:
      - vault_token
      - vault_keys_csv


