version: "3.9"

services:

  # Traefik for reverse proxy and load balancing
  traefik:
    image: traefik:v2.3
    ports:
        - "80:80"
    command:
      - --providers.docker.swarmmode
    deploy:
      placement:
        constraints:
          - node.role == manager # Deploy Traefik on a manager node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


  # Service for the OpenNews api
  api:
    image: spamz23/opennews:api

    # Command to start the server at port 8000
    command: gunicorn opennews.wsgi:application -b 0.0.0.0:8000

    deploy:
      labels:
        - traefik.http.services.en_core_web_sm.loadbalancer.server.port=80
        - traefik.http.routers.corporate.rule=Host(`api.onews.diogosilva.tech`) # Serve at api.onews.diogosilva.tech

    environment:
      # Use production settings
      DJANGO_SETTINGS_MODULE: opennews.settings.production
      VAULT_URL: http://vault:8200/
      VAULT_TOKEN: /run/secrets/vault_token # --------|
      VAULT_KEYS_CSV: /run/secrets/vault_keys_csv # --|-->File location of Docker secret

    # Mount secrets from Swarm Manager
    secrets:
      - vault_token
      - vault_keys_csv


  # Redis database to serve as a message broker between backend
  # and celeris worker
  redis:
    image: "redis:alpine"
    volumes:
      - "redis:/data"


  # Celery background worker
  celery:
    image: spamz23/opennews:api
    command: celery -A opennews worker -l info
    environment:
      # Use production settings
      DJANGO_SETTINGS_MODULE: opennews.settings.production
      VAULT_URL: http://vault:8200/
      VAULT_TOKEN: /run/secrets/vault_token # --------|
      VAULT_KEYS_CSV: /run/secrets/vault_keys_csv # --|-->File location of Docker secret
    # Mount secrets from Swarm Manager
    secrets:
      - vault_token
      - vault_keys_csv

    depends_on:
      - api
      - redis


  # Hashicorp vault for secret management
  vault:
    image: vault:1.8.4

    deploy:
      replicas: 1
      labels:
        - traefik.http.services.en_core_web_sm.loadbalancer.server.port=80
        - traefik.http.routers.corporate.rule=Host(`vault.onews.diogosilva.tech`) # Serve at vault.onews.diogosilva.tech

    environment:
      - VAULT_ADDR=http://127.0.0.1:8200 # Run on port 8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_LOCAL_CONFIG={"backend":{"file":{"path":"vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}},"ui":true, "disable_mlock":true}
    cap_add:
      - IPC_LOCK
    command: server
    volumes:
      - vault:/vault/file

volumes:
  redis:
  vault:
  
secrets:
  vault_token:
    external: true
  vault_keys_csv:
    external: true